apiVersion: v1
kind: Service
metadata:
  name: crud-node-app
spec:
  selector:
    app: crud-node-app
  ports:
  - port: 3000
    targetPort: web
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 2
    selector:
      matchLabels:
        app: crud-node-app
    template:
      metadata:
        labels:
            app: crud-node-app
      spec: 
        containers:
        - name: crud-app
          image: dossaan/crud-node:latest
          env:
            - name: host
              value: "postgres"
            - name: user
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: user
            - name: db
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: db
            - name: password
              valueFrom:
                secretKeyRef:
                  name: secret-config
                  key: password
            - name: greeting
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: greeting
          ports:
            - name: web
              containerPort: 80