apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  greeting: Salem, bari durys!
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-config
type: Opaque
data:
  user: {{ .Values.postgresql.username | b64enc }}
  db: {{ .Values.postgresql.db | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}